### ISSUE TITLE
what if the labels are images ? 

### ISSUE THREAD

**Issue by Ng-ms** [utkuozbulak/pytorch-custom-dataset-examples#4]
what to change in the custom dataset to make it work on images as ground truth not cvs file ?

**Comment by utkuozbulak** [comment]
Hey, 

Then you can just return two images represented as tensors. In the examples, after all the logic, instead of 

```python
return (img_as_tensor, single_image_label)
```
you will have
```python
return (img_as_tensor, target_as_tensor)
```

I was planning to include example for segmentation (i.e., return image, image) for a while, I will try to update the repository in the upcoming days to have an actual example.

**Comment by Ng-ms** [comment]
thank you utku , i am waiting for your rep ,
another question is it possible to show the segmented part as 3D with pytorch ?

**Comment by utkuozbulak** [comment]
Hey,

What do you mean by 'showing the segmented parts as 3d'? In terms of a custom dataset, 3d image is no different than 2d image. Instead of (Channel[1 or 3] x Height x Width) you return an image with (Slice x Height x Width). So, in most cases it has 3 dimensions.
